export 'nav/new/account/address_entry_screen.dart';
export 'forget_password_screen.dart';
export 'main_screen.dart';
export 'otp_screen.dart';
export 'partner_registration_screen.dart';
export 'sign_in_screen.dart';
export 'sign_up_screen.dart';
export 'splash_screen.dart';
export 'webview_adma_privacy_screen.dart';
