// decoration
const d_wave_br = "images/decorations/d_wave_br.svg";
const d_wave_tr = "images/decorations/d_wave_tr.svg";
const d_wave_tr_p = "images/decorations/d_wave_tr.png";

// icon
const ic_allcategory = "images/icons/allcategories.svg";
const ic_shop = "images/icons/ic_shop.svg";
const ic_sendorder = "images/icons/ic_sendorder.svg";
const ic_apmikimmdo = "images/icons/ic_apmikimmdo.svg";
const ic_apmikimmdo_png = "images/icons/ic_apmikimmdo.png";
const ic_menu = "images/icons/ic_menu.svg";
const ic_food_fill = "images/icons/ic_food_fill.svg";
const ic_food_fill_white = "images/icons/ic_food_fill_white.svg";
const ic_shop_fill = "images/icons/ic_shop_fill.svg";
const ic_reseller = "images/icons/ic_reseller.svg";
const ic_supplier = "images/icons/ic_supplier.svg";
const ic_horeca_fill = "images/icons/ic_horeca_fill.svg";
const ic_horeca = "images/icons/ic_horeca.svg";
const ic_dompet = "images/icons/ic_dompet.svg";
const ic_coin = "images/icons/ic_coin.svg";
const ic_voucher = "images/icons/ic_voucher.svg";
const ic_marker_map = "images/icons/ic_marker_map.svg";
const ic_voucher_horizontal = "images/icons/ic_voucher_horizontal.svg";
const ic_homemenu = "images/icons/ic_homemenu.svg";
const ic_homeactive = "images/icons/ic_homeactive.svg";
const ic_shopmenu = "images/icons/ic_shopmenu.svg";
const ic_shopactive = "images/icons/ic_shopactive.svg";
const ic_transactionmenu = "images/icons/ic_transactionmenu.svg";
const ic_transactionactive = "images/icons/ic_transactionactive.svg";
const ic_profilemenu = "images/icons/ic_profilemenu.svg";
const ic_profileactive = "images/icons/ic_profileactive.svg";
const ic_add_shop_product = "images/icons/ic_add_shop_product.svg";
const ic_logo_small = "images/icons/logo_apmikimmdo.svg";

// image
const img_clock = "images/img_clock.png";
const img_arrow = "images/img_arrow.png";
const img_logo_placeholder = "images/img_logo_placeholder.jpg";
const img_logo = "images/img_apmikimmdo_logo.png";
const img_logo_light = "images/img_apmikimmdo_light.png";
const img_logo_dark = "images/img_logo_dark.png";
const img_not_found = "images/img_not_found.png";
const img_open_shop = "images/img_open_shop.png";
const img_no_connection = "images/img_no_connection.png";
const img_default_account = "images/img_default_account.png";
const img_shop_product_empty = "images/img_shop_product_empty.png";
const img_error = "images/img_error.png";
const img_btn_gplay = "images/img_btn_gplay.png";
const img_btn_astore = "images/img_btn_astore.png";
const img_empty_user = "images/img_empty_user.png";
const img_cs = "images/img_cs.png";
const img_btn_fb = "images/img_btn_fb.png";
const img_btn_ig = "images/img_btn_ig.png";
const img_btn_tweet = "images/img_btn_tweet.png";
const img_pay_ads = "images/logo_adma.png";
const img_pay_americaex = "images/img_pay_americaex.png";
const img_pay_visa = "images/img_pay_visa.png";
const img_pay_bca = "images/img_pay_bca.png";
const img_pay_bni = "images/img_pay_bni.png";
const img_pay_gopay = "images/img_pay_gopay.png";
const img_pay_jcb = "images/img_pay_jcb.png";
const img_pay_mandiri = "images/img_pay_mandiri.png";
const img_pay_mastercard = "images/img_pay_mastercard.png";
const img_pay_permata = "images/img_pay_permata.png";
const img_pay_qris = "images/img_pay_qris.png";
const img_payment_success = "images/img_payment_success.png";
const img_add_shop_product = "images/img_add_shop_product.png";
const img_homepage_warung = "images/img_homepage_warung.png";
const img_delivery_road = "images/img_delivery_road.png";
const img_product_error = "images/img_product_error.png";

// image layanan kami
const ic_mui = "images/ic_mui.png";
const ic_nib = "images/ic_nib.png";
const ic_bpom = "images/ic_bpom.png";
const ic_kopukm = "images/ic_kopukm.png";
const ic_pirt = "images/ic_pirt.png";
